# Generated by Django 4.1 on 2024-09-01 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artist', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='address',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='gender',
        ),
    ]
